// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwJ4BAIxS5pz6yDEOcYVd4QBK0GAP9Mx8',
    appId: '1:307748362091:web:b481abfc855226ac605e2e',
    messagingSenderId: '307748362091',
    projectId: 'pdfscanner-project',
    authDomain: 'pdfscanner-project.firebaseapp.com',
    databaseURL: 'https://pdfscanner-project-default-rtdb.firebaseio.com',
    storageBucket: 'pdfscanner-project.firebasestorage.app',
    measurementId: 'G-0H19Y70ZD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD4QADA9P6QtbIIBNOccD3aK-UX8Qo93A',
    appId: '1:307748362091:android:42f373a41e9b09ed605e2e',
    messagingSenderId: '307748362091',
    projectId: 'pdfscanner-project',
    databaseURL: 'https://pdfscanner-project-default-rtdb.firebaseio.com',
    storageBucket: 'pdfscanner-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCptBhE39AVKdg4aID2Qhp-49Fi61XAtag',
    appId: '1:307748362091:ios:1de669a9fd55d655605e2e',
    messagingSenderId: '307748362091',
    projectId: 'pdfscanner-project',
    databaseURL: 'https://pdfscanner-project-default-rtdb.firebaseio.com',
    storageBucket: 'pdfscanner-project.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

}